[package]
name = "log_demo"
version = "0.1.0"
authors = []
license = ""

[build]
target = "native"
mutate = true
debug = false
ccache = true

[optimize]
enabled = true
pgo = false
strip = true
tune_host = false
gc_sections = true

[test]
property_rounds = 1000

[style]
line_length = 90
