#!/usr/bin/env python3
"""Extract node type constants from tree-sitter's node-types.json.

Generates:
  - constants/node_kinds.py  — Python dict of node type names
  - constants/node_kinds.h   — C #define constants

These are generated artifacts, committed to the repo, rebuilt by:
  tree-sitter generate && python scripts/extract_constants.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
TS_DIR = HERE.parent
CONSTANTS_DIR = TS_DIR / "constants"
NODE_TYPES_PATH = TS_DIR / "src" / "node-types.json"


def load_named_types() -> list[str]:
    """Load named node types from node-types.json."""
    with NODE_TYPES_PATH.open() as f:
        data = json.load(f)
    return sorted(item["type"] for item in data if item.get("named"))


def to_c_name(node_type: str) -> str:
    """Convert a node type name to a C constant name."""
    return "PROVE_NODE_" + node_type.upper()


def generate_python(types: list[str]) -> str:
    """Generate Python constants file."""
    lines = [
        '"""Node type constants for tree-sitter-prove.',
        "",
        "Auto-generated by scripts/extract_constants.py — do not edit.",
        '"""',
        "",
        "NODE_KINDS: dict[str, str] = {",
    ]
    for t in types:
        lines.append(f'    "{t.upper()}": "{t}",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_c_header(types: list[str]) -> str:
    """Generate C header file."""
    lines = [
        "/*",
        " * Node type constants for tree-sitter-prove.",
        " *",
        " * Auto-generated by scripts/extract_constants.py — do not edit.",
        " */",
        "",
        "#ifndef PROVE_NODE_KINDS_H",
        "#define PROVE_NODE_KINDS_H",
        "",
    ]
    for t in types:
        c_name = to_c_name(t)
        lines.append(f'#define {c_name} "{t}"')
    lines.append("")
    lines.append("#endif /* PROVE_NODE_KINDS_H */")
    lines.append("")
    return "\n".join(lines)


def main():
    types = load_named_types()
    print(f"Extracted {len(types)} named node types from {NODE_TYPES_PATH.name}")

    CONSTANTS_DIR.mkdir(exist_ok=True)

    py_path = CONSTANTS_DIR / "node_kinds.py"
    py_path.write_text(generate_python(types))
    print(f"  wrote {py_path.relative_to(TS_DIR)}")

    h_path = CONSTANTS_DIR / "node_kinds.h"
    h_path.write_text(generate_c_header(types))
    print(f"  wrote {h_path.relative_to(TS_DIR)}")


if __name__ == "__main__":
    main()
