"""Automatic Python package bundling for foreign libpython3 modules.

When the compiler detects a module that uses `foreign "libpython3"` and has
comptime-read `.py` files, this module:
  1. Scans those .py entry points for Python imports (transitively via AST)
  2. Resolves each import to its installed location via importlib
  3. Skips stdlib packages (only bundles third-party site-packages)
  4. Zips all .py files from the found packages
  5. Writes prove_bundle_data.h as a C byte array into the build gen dir

The generated header is then #included by py_wrappers.c, which writes the
zip to a temp file and prepends it to sys.path at runtime.
"""

from __future__ import annotations

import ast
import importlib.util
import io
import os
import zipfile
from pathlib import Path


def _parse_imports(py_file: Path) -> set[str]:
    """Return top-level package names imported by a single .py file."""
    try:
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return set()

    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                names.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.level == 0:
                names.add(node.module.split(".")[0])
    return names


def _collect_entry_imports(py_files: set[Path]) -> set[str]:
    """Collect all top-level package names imported by the entry .py files."""
    names: set[str] = set()
    for f in py_files:
        names.update(_parse_imports(f))
    return names


def _find_third_party_packages(names: set[str]) -> dict[str, Path]:
    """Map package name → package root directory for non-stdlib packages.

    Skips stdlib modules (via sys.stdlib_module_names) and built-ins.
    Includes editable installs whose source lives outside site-packages.
    """
    import sys

    stdlib_names: frozenset[str] = getattr(sys, "stdlib_module_names", frozenset())
    result: dict[str, Path] = {}

    for name in sorted(names):
        if name in stdlib_names or name in sys.builtin_module_names:
            continue
        try:
            spec = importlib.util.find_spec(name)
        except (ModuleNotFoundError, ValueError):
            continue
        if spec is None or not spec.submodule_search_locations:
            continue

        pkg_path = Path(next(iter(spec.submodule_search_locations))).resolve()
        result[name] = pkg_path

    return result


_SKIP_SUFFIXES = frozenset({".pyc", ".pyo"})
_SKIP_DIRS = frozenset({"__pycache__"})


def _zip_packages(packages: dict[str, Path]) -> bytes:
    """Create a zip archive containing all package data from the given packages.

    Includes .py source files AND package data files (e.g. .prv stdlib sources
    read via importlib.resources). Skips compiled bytecode and __pycache__.

    Uses os.walk with followlinks=True so that symlinked sub-packages (e.g.
    prove/runtime -> proof/src/runtime) are included in the archive.

    The archive uses paths relative to each package's parent so that
    `import prove` works after adding the zip to sys.path.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for _name, pkg_root in sorted(packages.items()):
            parent = pkg_root.parent
            for dirpath, dirnames, filenames in os.walk(pkg_root, followlinks=True):
                dirnames[:] = [d for d in sorted(dirnames) if d not in _SKIP_DIRS]
                for fname in sorted(filenames):
                    f = Path(dirpath) / fname
                    if f.suffix in _SKIP_SUFFIXES:
                        continue
                    zf.write(f, str(f.relative_to(parent)))
    return buf.getvalue()


def _write_c_header(data: bytes, out_path: Path) -> None:
    """Write the zip bytes as a C header with a static byte array."""
    lines = [
        "/* Auto-generated by prove compiler — do not edit. */\n",
        "/* Re-generated on every `prove build` that uses foreign libpython3. */\n",
        "#pragma once\n",
        "#include <stddef.h>\n\n",
        "static const unsigned char prove_bundle_zip[] = {\n",
    ]
    for i, b in enumerate(data):
        if i % 16 == 0:
            lines.append("    ")
        lines.append(f"0x{b:02x},")
        lines.append("\n" if i % 16 == 15 else " ")
    if len(data) % 16 != 0:
        lines.append("\n")
    lines.append("};\n")
    lines.append(f"static const size_t prove_bundle_zip_len = {len(data)};\n")
    out_path.write_text("".join(lines))


def maybe_generate_bundle(
    modules_and_symbols: list,
    comptime_deps: set[Path],
    gen_dir: Path,
) -> bool:
    """Generate prove_bundle_data.h if the project embeds Python.

    Returns True if the header was written, False if the project does not
    use foreign libpython3 (no-op for projects that don't embed Python).

    Raises SystemExit with a clear message if no bundleable packages are found
    so the error surfaces before C compilation rather than as a runtime crash.
    """
    from prove.ast_nodes import ModuleDecl

    # Detect foreign "libpython3" in any module
    uses_libpython = any(
        fb.library == "libpython3"
        for module, _ in modules_and_symbols
        for decl in module.declarations
        if isinstance(decl, ModuleDecl)
        for fb in decl.foreign_blocks
    )
    if not uses_libpython:
        return False

    py_entry_files = {p for p in comptime_deps if p.suffix == ".py"}
    if not py_entry_files:
        return False

    import_names = _collect_entry_imports(py_entry_files)
    packages = _find_third_party_packages(import_names)

    if not packages:
        raise SystemExit(
            "error: foreign libpython3 detected but no bundleable packages found.\n"
            "       Make sure the required packages are installed in the active venv.\n"
            f"       Scanned imports: {sorted(import_names)}"
        )

    # If all found packages live inside a zip (i.e. we are already running from
    # a bundle), skip regeneration — the binary already has the bundle baked in.
    if all(not pkg_path.is_dir() for pkg_path in packages.values()):
        return False

    data = _zip_packages(packages)
    out_path = gen_dir / "prove_bundle_data.h"
    _write_c_header(data, out_path)

    pkg_names = ", ".join(sorted(packages))
    total_files = sum(
        1
        for p in packages.values()
        for _, _, filenames in os.walk(p, followlinks=True)
        for fname in filenames
        if not fname.endswith(tuple(_SKIP_SUFFIXES))
    )
    print(f"bundled python packages [{pkg_names}] → {total_files} files, {len(data):,} bytes")
    return True
