"""Prove lockfile (prove.lock) reading and writing.

The lockfile pins exact versions + checksums for all dependencies.
Format is TOML-like, produced via string templates (no writer lib needed).
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class LockedPackage:
    name: str
    version: str
    checksum: str  # "sha256:..."
    source: str  # URL to .prvpkg


@dataclass
class Lockfile:
    prove_version: str
    packages: list[LockedPackage] = field(default_factory=list)


def read_lockfile(path: Path) -> Lockfile | None:
    """Parse a prove.lock file. Returns None if file doesn't exist."""
    if not path.exists():
        return None

    with open(path, "rb") as f:
        data = tomllib.load(f)

    packages = []
    for pkg in data.get("package", []):
        packages.append(
            LockedPackage(
                name=pkg["name"],
                version=pkg["version"],
                checksum=pkg.get("checksum", ""),
                source=pkg.get("source", ""),
            )
        )

    return Lockfile(
        prove_version=data.get("prove_version", ""),
        packages=packages,
    )


def write_lockfile(path: Path, lockfile: Lockfile) -> None:
    """Write a prove.lock file using string templates."""
    lines = [
        "# This file is auto-generated by `prove package`. Do not edit.",
        f'prove_version = "{lockfile.prove_version}"',
        "",
    ]

    for pkg in lockfile.packages:
        lines.append("[[package]]")
        lines.append(f'name = "{pkg.name}"')
        lines.append(f'version = "{pkg.version}"')
        lines.append(f'checksum = "{pkg.checksum}"')
        lines.append(f'source = "{pkg.source}"')
        lines.append("")

    path.write_text("\n".join(lines))


def lockfile_is_stale(
    lockfile: Lockfile,
    dependencies: list[tuple[str, str]],
) -> bool:
    """Check if the lockfile is out of date with respect to declared dependencies.

    Returns True if any dependency is missing from the lockfile or if the
    lockfile contains packages not in the dependency list.
    """
    locked_names = {pkg.name for pkg in lockfile.packages}
    dep_names = {name for name, _ in dependencies}

    # Missing or extra packages
    if locked_names != dep_names:
        return True

    # Check version constraints (simple exact match for now)
    locked_versions = {pkg.name: pkg.version for pkg in lockfile.packages}
    for name, constraint in dependencies:
        if name not in locked_versions:
            return True
        # If constraint is exact version, check match
        if not constraint.startswith((">=", "^", "<", ">")):
            if locked_versions[name] != constraint:
                return True

    return False
