"""Phase 3 — Model Storage via Store Stdlib (Python bridge).

Reads trained JSON models and writes them as Prove :[Lookup] table files
into data/lsp-ml-store/ in the Store format expected by the LSP.

Table layout:
    data/lsp-ml-store/
        bigrams/
            current.prv   ← (prev1, next_token) → count
            versions/
        completions/
            current.prv   ← (prev2, prev1) → pipe-separated ranked list
            versions/

Usage:
    python scripts/ml_store.py [--top-k 5]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_STORE_DIR = _REPO_ROOT / "data" / "lsp-ml-store"


def _prv_str(value: str) -> str:
    """Encode a Python string as a Prove string literal."""
    # Escape backslash and double-quote
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _row_id(index: int) -> str:
    """Generate a valid Prove identifier for a table row."""
    return f"r{index:05d}"


def write_bigrams_table(unigram_model: dict, top_k: int, out_path: Path) -> int:
    """Write (prev1, next_token) → count as a :[Lookup] table.

    Returns number of rows written.
    """
    rows: list[tuple[str, str, int]] = []
    for prev1, entries in unigram_model.items():
        for next_tok, count in entries[:top_k]:
            rows.append((prev1, next_tok, count))

    lines = [
        "// Bigram frequency table for LSP ML completions",
        "// (prev_token, next_token) → frequency count",
        "// Auto-generated by scripts/ml_store.py — do not edit by hand",
        "type Bigram:[Lookup] is String String Integer where",
    ]
    for i, (prev1, next_tok, count) in enumerate(rows):
        row_id = _row_id(i)
        lines.append(f"    {row_id} | {_prv_str(prev1)} | {_prv_str(next_tok)} | {count}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    (out_path.parent / "versions").mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rows)


def write_completions_table(bigram_model: dict, top_k: int, out_path: Path) -> int:
    """Write (prev2, prev1) → pipe-separated top tokens as a :[Lookup] table.

    Returns number of rows written.
    """
    lines = [
        "// Completion context table for LSP ML completions",
        "// (prev2, prev1) → pipe-separated ranked completion list",
        "// Auto-generated by scripts/ml_store.py — do not edit by hand",
        "type Completion:[Lookup] is String String String where",
    ]
    row_count = 0
    for i, (key_json, entries) in enumerate(bigram_model.items()):
        prev2, prev1 = json.loads(key_json)
        top_tokens = [tok for tok, _count in entries[:top_k]]
        completion_str = "|".join(top_tokens)
        row_id = _row_id(i)
        lines.append(
            f"    {row_id} | {_prv_str(prev2)} | {_prv_str(prev1)} | {_prv_str(completion_str)}"
        )
        row_count += 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    (out_path.parent / "versions").mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return row_count


def write_docstring_table(docstring_index: dict, out_path: Path) -> int:
    """Write keyword -> (module, function, verb, docstring) as a :[Lookup] table.

    Returns number of rows written.
    """
    lines = [
        "// Docstring knowledge base for LSP intent completions",
        "// keyword | module | function | verb | docstring",
        "// Auto-generated by scripts/ml_store.py — do not edit by hand",
        "type DocstringMap:[Lookup] is String String String String String where",
    ]
    row_count = 0
    for keyword in sorted(docstring_index):
        for entry in docstring_index[keyword]:
            row_id = _row_id(row_count)
            lines.append(
                f"    {row_id} | {_prv_str(keyword)} | {_prv_str(entry['module'])} "
                f"| {_prv_str(entry['name'])} | {_prv_str(entry['verb'])} "
                f"| {_prv_str(entry['doc'])}"
            )
            row_count += 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    (out_path.parent / "versions").mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return row_count


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top-k", type=int, default=5, dest="top_k",
                        help="Max completions per context (default: 5)")
    parser.add_argument("--data-dir", default="data")
    args = parser.parse_args()

    data_dir = _REPO_ROOT / args.data_dir

    completions_model_path = data_dir / "completions_model.json"
    bigrams_model_path = data_dir / "bigrams_model.json"
    docstrings_model_path = data_dir / "docstring_index.json"

    print(f"Loading {completions_model_path} ...")
    with open(completions_model_path, encoding="utf-8") as f:
        bigram_model = json.load(f)

    print(f"Loading {bigrams_model_path} ...")
    with open(bigrams_model_path, encoding="utf-8") as f:
        unigram_model = json.load(f)

    bigrams_out = _STORE_DIR / "bigrams" / "current.prv"
    completions_out = _STORE_DIR / "completions" / "current.prv"
    docstrings_out = _STORE_DIR / "docstrings" / "current.prv"

    print(f"Writing bigrams table → {bigrams_out}")
    n_bigram_rows = write_bigrams_table(unigram_model, args.top_k, bigrams_out)
    print(f"  {n_bigram_rows} rows")

    print(f"Writing completions table → {completions_out}")
    n_completion_rows = write_completions_table(bigram_model, args.top_k, completions_out)
    print(f"  {n_completion_rows} rows")

    if docstrings_model_path.exists():
        print(f"Loading {docstrings_model_path} ...")
        with open(docstrings_model_path, encoding="utf-8") as f:
            docstring_index = json.load(f)
        print(f"Writing docstrings table → {docstrings_out}")
        n_docstring_rows = write_docstring_table(docstring_index, docstrings_out)
        print(f"  {n_docstring_rows} rows")
    else:
        print(f"Skipping docstrings (no {docstrings_model_path})")

    # Verify the files are readable and look sane
    verify_paths = [bigrams_out, completions_out]
    if docstrings_out.exists():
        verify_paths.append(docstrings_out)
    for path in verify_paths:
        text = path.read_text(encoding="utf-8")
        row_lines = [l for l in text.splitlines() if l.strip().startswith("r")]
        print(f"\n{path.relative_to(_REPO_ROOT)}: {len(row_lines)} rows, first 3:")
        for line in row_lines[:3]:
            print(f"  {line.strip()}")


if __name__ == "__main__":
    main()
